# build image
# docker build -t einkaufsliste_backend .

# Basis-Image mit Python
FROM python:3.13-slim

# Arbeitsverzeichnis im Container setzen
WORKDIR /app

# Abhängigkeiten hinzufügen
COPY requirements.txt .

# Installieren der Python-Bibliotheken
RUN pip install --no-cache-dir -r requirements.txt

# Application Code kopieren
COPY . .

# Startbefehl für das Backend
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
