name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx pytest

      - name: Start Docker Compose
        run: |
          cd backend
          docker-compose up --build -d
        timeout-minutes: 3

      - name: Wait for services to be healthy
        run: |
          docker-compose ps
          sleep 10  # optional: du kannst hier auch Healthchecks machen oder abfragen

      - name: Run Pytest
        run: |
          cd backend/test
          python3 -m pytest

      - name: Shut down Docker Compose
        if: always()
        run: |
          docker-compose down
